INSERT INTO ESTADOS (ID, NOME, SIGLA, POPULACAO) VALUES (1000, 'NOVO', 'NV', 2.54);


INSERT INTO ESTADOS (NOME, SIGLA, REGIAO, POPULACAO) VALUES ('MAISNOVO', 'MN', 'SUL', 2.99); 

SELECT * FROM ESTADOS;